# Generated by Django 2.2 on 2019-04-06 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfTestee', models.CharField(max_length=30, verbose_name='First Name of Testee')),
                ('emailOfTestee', models.EmailField(max_length=50, verbose_name='Email of Testee')),
                ('startOfTestDatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start of Test Date and Time')),
                ('startOfStep1Time', models.TimeField(default=django.utils.timezone.now, verbose_name='Start of Step 1 Time')),
                ('step1Score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2, verbose_name='Step 1 Score')),
                ('endOfStep1Time', models.TimeField(default=django.utils.timezone.now, verbose_name='End of Step 1 Time')),
                ('step2Score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2, verbose_name='Step 2 Score')),
                ('step3Score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2, verbose_name='Step 3 Score')),
                ('step4Score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2, verbose_name='Step 4 Score')),
                ('step5Score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2, verbose_name='Step 5 Score')),
                ('startOfStep6Time', models.TimeField(default=django.utils.timezone.now, verbose_name='Start of Step 6 Time')),
                ('step6Score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2, verbose_name='Step 6 Score')),
                ('endOfStep6Time', models.TimeField(default=django.utils.timezone.now, verbose_name='End of Step 6 Time')),
                ('startOfStep7Time', models.TimeField(default=django.utils.timezone.now, verbose_name='Start of Step 7 Time')),
                ('step7Score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2, verbose_name='Step 7 Score')),
                ('endOfStep7Time', models.TimeField(default=django.utils.timezone.now, verbose_name='End of Step 7 Time')),
                ('startOfStep8aTime', models.TimeField(default=django.utils.timezone.now, verbose_name='Start of Step 8a Time')),
                ('step8aScore', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2, verbose_name='Step 8a Score')),
                ('endOfStep8aTime', models.TimeField(default=django.utils.timezone.now, verbose_name='End of Step 8a Time')),
                ('startOfStep8bTime', models.TimeField(default=django.utils.timezone.now, verbose_name='Start of Step 8b Time')),
                ('step8bScore', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2, verbose_name='Step 8b Score')),
                ('endOfStep8bTime', models.TimeField(default=django.utils.timezone.now, verbose_name='End of Step 8b Time')),
                ('step9Score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2, verbose_name='Step 9 Score')),
                ('step10Score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2, verbose_name='Step 10 Score')),
                ('additionalComments', models.TextField(blank=True, max_length=500)),
                ('totalScore', models.IntegerField(default=0, verbose_name='Total Score')),
                ('nameOfTester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID of Test Conductor')),
            ],
        ),
    ]
